### PR TITLE
added Forcefield.apply assert_bonds

### PR DESCRIPTION
**Pull request by richardjgowers**

### CODE REVIEW

**Comment by mattwthompson** [comment]
Thanks for the contribution!

My understand was that it's supposed to get caught earlier (see [here](https://github.com/mosdef-hub/foyer/pull/155#issuecomment-356496022)) but I know you're dealing with topologically different systems than we were using back then. I'm a little fuzzy on this so I will let @summeraz comment.

**Comment by richardjgowers** [comment]
It looks like that comment says it gets picked up in the MD engine later on.  Arguably this is a thing for foyer to spot.

Looks like this change breaks an existing test, I think you all can push to this branch to fix

**Comment by richardjgowers** [comment]
@summeraz I've added a test, it's possible to do `Forcefield.apply()` and get bonds with no parameters

**Comment by mikemhenry** [comment]
Why did this PR not go through CI?

**Comment by mattwthompson** [comment]
Oops, that was sloppy. We thought it was one of the tests that can fail for silly reasons, but on further inspection it's actually something we need to change. Thanks for catching this

**Comment by mikemhenry** [comment]
No worries! I was just surprised that while I was working on another PR, that test started to fail. It looks like this PR was really needed, since one of the tests didn't have all the bonds defined.

**Comment by mattwthompson** [comment]
Yeah, of all the things that can happen with failing units tests, finding and fixing an unrelated issue is among the better outcomes

**Pull request merged**
