### PR TITLE
Switch from oset OrderedSet to boltons IndexedSet

### PR DESCRIPTION
**Pull request by mattwthompson**
In the spirit of using packages that have been updated in the past 5 years (https://pypi.org/project/oset/#history)

#205

### CODE REVIEW

**Comment by ctk3b** [comment]
Quick question: do we still rely on the ordered nature of the white/black list? A quick scan through the code suggests no. Perhaps it _slightly_ aids when debugging?

**Comment by mattwthompson** [comment]
You're more familiar with that than me but I agree with your assessment that the order doesn't seem to matter at the moment. Were those lists `OrderedSet` instead of `set` before because it used a different way of solving the atomtyping problem?

**Comment by mattwthompson** [comment]
Just using built-in `set` works for me locally, I will open that as a PR if the build passes on my fork https://travis-ci.org/mattwthompson/foyer/builds/518369398

**Comment by ctk3b** [comment]
> Were those lists OrderedSet instead of set before because it used a different way of solving the atomtyping problem?

I honestly don't remember. At the end of the day, we always used a set diff to check if we had converged. I suspect we had used this to aid in debugging back when this was a lot less stable and we were still working on edge cases in the atomtyping logic itself.

**Comment by justinGilmer** [comment]
Taken care of by #231

**Pull request closed without merging**
