### PR TITLE
Feat/skip empty def

### LINKED ISSUE #179: Should foyer skip an empty def field?
In order to make a foyer force field file more template-y I propose that foyer should skip an empty def field.   

`<Type name="opls_001" class="C" element="C" mass="12.0107" def="" desc="" doi=""/>`

That way it suggests to someone looking at this file that: 

1. `opls_001` is missing a `def`
1. This file is obviously a foyer force field file
1. The empty fields should be filled in 

I'd be interested in hearing the cos for this. We can keep the current behavior where a type missing an `def` is ignored, but this would make things more explicit.

Thoughts?

I was thinking the logic could be added here:
https://github.com/mosdef-hub/foyer/blob/master/foyer/forcefield.py#L329-L330

But I'm not super familiar with foyer so if we decide to do this I might need some guidance in writing the PR.

### PR DESCRIPTION
**Pull request by mikemhenry**
Fixes #179 

Had to add a skip in two locations, so I doubt this is an optimal solution.

Also, I'm not sure what's going on with the validation test:

```
tests/test_validator.py::test_xmls[foyer/tests/files/warning_missingsmarts.xml] FAILD
 @pytest.mark.parametrize('ff_file', XMLS)
    def test_xmls(ff_file):
        file_name = os.path.split(ff_file)[1]
        if 'error' in file_name:
            error_type = ERRORS[file_name.split('_')[0]]
            with pytest.raises(error_type):
                Validator(ff_file)
        elif file_name.startswith('warning'):
            with pytest.warns(ValidationWarning):
>               Validator(ff_file)
E               Failed: DID NOT WARN. No warnings of type (<class 'foyer.exceptions.ValidationWarning'>,) was emitted. 
The list of emitted warnings is: 
[DeprecationWarning("invalid escape sequence '\\#'",),
DeprecationWarning("invalid escape sequence '\\['",), 
DeprecationWarning("invalid escape sequence '\\]'",),
DeprecationWarning("invalid escape sequence '\\('",), 
DeprecationWarning("invalid escape sequence '\\)'",), 
DeprecationWarning("invalid escape sequence '\\,'",),
DeprecationWarning("invalid escape sequence '\\;'",), 
DeprecationWarning("invalid escape sequence '\\&'",), 
DeprecationWarning("invalid escape sequence '\\*'",), 
DeprecationWarning("invalid escape sequence '\\$'",), 
DeprecationWarning("invalid escape sequence '\\d'",), 
DeprecationWarning("invalid escape sequence '\\%'",), 
DeprecationWarning("invalid escape sequence '\\!'",)].
```

Even if I add `warn("You have empty smart definition(s)", ValidationWarning)` which I have left commented out in the PR.

### CODE REVIEW

**Comment by mattwthompson** [comment]
Those deprecation warnings are probably from plyplus with Python > 3.5

**Comment by mikemhenry** [comment]
Yah sorry I wasn't clear, this test failed `[foyer/tests/files/warning_missingsmarts.xml]` since it didn't throw a `foyer.exceptions.ValidationWarning`.

**Comment by mikemhenry** [comment]
I took another look at this PR and this test was designed to check if SMARTS was missing and since it can now be empty it fails. If a SMARTS definition is missing, should I throw that warning still? Or delete the test?

**Comment by mattwthompson** [comment]
Hmm, passing on 3.5 but failing on 2.7 (both macOS and Linux)

**Comment by mikemhenry** [comment]
Yah I have no idea why 2.7 the warning doesn't get thrown, is like to add
the same python versions mbuild is tested for to see if it's just 2.7 or
something else

**Comment by mattwthompson** [comment]
Restarted travis and 2.7 is still failing 🤔

**Comment by mikemhenry** [comment]
Weird, I'll need to look into if 2.7 does something different with the
warnings/maybe a different version of pytest?

**Comment by mikemhenry** [comment]
Okay with the update to lark, I had to make a small change with how this worked, but now its ready for review.

**Comment by mikemhenry** [comment]
Tried a few more things but I can't seem to figure out why this doesn't work for python2. This isn't what the issue is https://github.com/pytest-dev/pytest/issues/2917 but indicates to me that there are some subtle differences between python2 and python3 warnings and what gets automatically filtered.

**Comment by mikemhenry** [comment]
Can this get merged in before too much work is done on Issue #255 Also should I drop 2.7 from testing in the PR?

**Comment by mattwthompson** [comment]
Don't worry about the 2.7 failures. Although it's interesting you're getting the opposite results compared to master, which has passing travis and failing Appveyor.

**Pull request merged**
