### PR TITLE
Support Python 3.6

### PR DESCRIPTION
**Pull request by mattwthompson**
Python 3.6 has been around for a while - and even Python 3.7 isn't too new - so we should start trying to support it.

This will probably require https://github.com/mosdef-hub/mbuild/pull/457 and https://github.com/mosdef-hub/mbuild/pull/435 to be merged first and then an mbuild release.

I am temporarily getting around plyplus issues (#172) by hosting builds on my own Anaconda channel; I will move those to the mosdef channel if it becomes necessary.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Anything blocking this PR?

**Comment by mattwthompson** [comment]
Yeah, we need to add each package to Anaconda but we can't do one before doing the other. And host plyplus on the official channel. A shotgun approach of just releasing them separately and hoping their tests pass might work, but that risks putting out builds that don't pass their own tests.

**Comment by mikemhenry** [comment]
Adding the deps needed to a mosdef channel is the right thing to do, you could even added the noarch flag so this doesn't keep happening (or just bump the python version if you don't want to change anything). 

I know hosting these isn't ideal, but many of these seem to be pure python packages that install just fine with pip, is there a way to tell conda to use pip to install them? Right now its really hard to use mBuild and foyer in new projects that I have going that are in python3.6

**Comment by mattwthompson** [comment]
Closed #204

**Pull request closed without merging**
