### PR TITLE
add python 3.12 and macOS-13 to test matrix

### PR DESCRIPTION
**Pull request by chrisjonesBSU**
### PR Summary:

mBuild and GMSO have started testing with python 3.12 and both versions of MacOS, we should do that here as well.

### PR Checklist
------------
 - [ ] Includes appropriate unit test(s)
 - [ ] Appropriate docstring(s) are added/updated
 - [ ] Code is (approximately) PEP8 compliant
 - [ ] Issue(s) raised/addressed?

### CODE REVIEW

**Comment by chrisjonesBSU** [comment]
The 3.12 tests won't pass until we change the gmso feedstock to pull 3.12

**Comment by chrisjonesBSU** [comment]
The failing test is caused because `mdtraj` is not reading or adding the bonds from the `ethane_customtype.pdb` we are using in `test_from_mbuild_customtype`.

The behavior is different between mdtraj 1.9.9 and mdtraj 1.10, but I don't think it's a general bug related to reading bonds from pdb files. If I use the `ch3.pdb` we have in mbuild's library, both versions of mdtraj read the bonds as expected.


**Using mdtraj 1.9.9:**

```
>>> import mdtraj as md
>>> ethane = md.load("ethane_customtype.pdb")
>>> ethane.top.n_bonds
7
>>>
```

**Using mdtraj 1.10.0:**

```
>>> import mdtraj as md
>>> ethane = md.load("ethane_customtype.pdb")
>>> ethane.top.n_bonds
0
>>>
```

**Comment by chrisjonesBSU** [comment]
Some tests are failing if they use the latest gmso, which has a bug where hoomd needs to be imported for anything using `gmso.external`

Fix is here: https://github.com/mosdef-hub/gmso/pull/828

**Comment by daico007** [comment]
I feel the amount of CI tests are running out of hand. I gonna reduce the tests matrix down a bit (only do python versions tests on linux and platforms tests on the latest python version).

**Comment by chrisjonesBSU** [comment]
> I feel the amount of CI tests are running out of hand. I gonna reduce the tests matrix down a bit (only do python versions tests on linux and platforms tests on the latest python version).

That's a good idea!

**Comment by chrisjonesBSU** [comment]
> I feel the amount of CI tests are running out of hand. I gonna reduce the tests matrix down a bit (only do python versions tests on linux and platforms tests on the latest python version).

This should be implemented now.

**Review by daico007 — APPROVED** [review]
LGTM! We can probably propagate this to mbuild and gmso too

**Pull request merged**
