### PR TITLE
Parmed customelement fix

### PR DESCRIPTION
**Pull request by ahy3nz**
Read custom atom types from pdb, correctly create elements based on element names in non_element_types

### CODE REVIEW

**Comment by ctk3b** [comment]
This looks good, thank you! Could you also file an issue on mBuild outlining the problem you found with uppercasing the names when starting with an mBuild compound loaded by a .pdb?

One last thing to fix though which is breaking appveyor: add a line here that also includes `*.pdb`

https://github.com/mosdef-hub/foyer/blob/master/setup.py#L90

**Comment by ctk3b** [comment]
Two more. We should probably fix this more elegantly in the near future.

https://github.com/mosdef-hub/foyer/blob/master/MANIFEST.in
https://github.com/mosdef-hub/foyer/blob/master/devtools/conda-recipe/meta.yaml#L33

**Comment by ahy3nz** [comment]
https://github.com/mosdef-hub/foyer/blob/master/devtools/conda-recipe/meta.yaml#L36
Is the meta.yaml file already looking for files in foyer/tests/files?

**Comment by ctk3b** [comment]
Oh yeah sorry, I was thinking it should technically also require the trappe_validation folder but the fact that it isn't causing errors suggests it's unnecessary.

**Comment by ahy3nz** [comment]
It looks all the checks have passed, is there anything else that needs to be done?

**Comment by ctk3b** [comment]
Great, thank you @ahy3nz !

**Pull request merged**
