### PR TITLE
Azure Pipelines as CI

### PR DESCRIPTION
**Pull request by umesh-timalsina**
### PR Summary:
Adding Azure Pipelines as a new CI.

This is a draft PR for azure pipelines integration with foyer.
### PR Checklist
------------
 - [ ] Includes appropriate unit test(s)
 - [ ] Appropriate docstring(s) are added/updated
 - [ ] Code is (approximately) PEP8 compliant
 - [ ] Issue(s) raised/addressed?

### CODE REVIEW

**Comment by umesh-timalsina** [comment]
Eventhough, the tests are failing, I think this PR is ready to be merged.
1. It has all tests along with a separate job for bleeding `mbuild`
2. It favors `cmd` to test in windows vs `powershell` also, it has a `cron` schedule that runs daily regardless of the code changes.

**Comment by mattwthompson** [comment]
Could you merge `master` in?

**Comment by uppittu11** [comment]
Why is the AZP Windows_no_bleeding Python36 from the previous build still showing up in the status checks? This is happening in [mbuild](https://github.com/mosdef-hub/mbuild/pull/618/checks?check_run_id=264017733) too. 

Otherwise I think this is good to go. Feel free to merge this; I'll add in codecov/pytest results upload bit at some point, but I don't want to hold back this PR

**Comment by mattwthompson** [comment]
Thanks @umesh-timalsina!

**Pull request merged**
