### PR TITLE
drop general forcefield

### PR DESCRIPTION
**Pull request by daico007**
### PR Summary:
With the new GMSO-centric workflow (foyer will be used purely for atomtyping), it has been decided that general_forcefield is no longer needed. This PR removed the general_forcefield and its related tests.

### PR Checklist
------------
 - [ ] Includes appropriate unit test(s)
 - [ ] Appropriate docstring(s) are added/updated
 - [ ] Code is (approximately) PEP8 compliant
 - [ ] Issue(s) raised/addressed?

### CODE REVIEW

**Review by CalCraven — APPROVED** [review]
Sounds good, this will reduce a lot of the testing burden we would need and move it to GMSO, where it should be. We probably need a forcefield-utilities backend loader now in Foyer, but that should be another PR. I can get to it after GMSO is covered.

**Comment by CalCraven** [comment]
Is there anything in the Foyer docs about general_forcefield?

**Comment by daico007** [comment]
I don't think we added any docs for the `general_forcefield` (we should have), but I guess it mean less thing to clean up now

**Comment by daico007** [comment]
now also update the atomclass in the `oplsaa.xml` (since this https://github.com/mosdef-hub/foyer/pull/474 is closed)

**Pull request merged**
