### PR TITLE
 Store atomtyping results in a dict instead of the topology

### PR DESCRIPTION
**Pull request by mattwthompson**
### PR Summary:
Implements @ctk3b's idea in #233

Not all tests are passing (some residue map and override stuff needs to be updated) but the basic cases are handled.

### PR Checklist
------------
 - [x] Includes appropriate unit test(s)
 - [x] Appropriate docstring(s) are added/updated
 - [x] Code is (approximately) PEP8 compliant
 - [x] Issue(s) raised/addressed?

### CODE REVIEW

**Comment by mattwthompson** [comment]
This PR accomplishes what I wanted to do, but the organization of the various functions could be improved upon. As you can see, the unit test now looks quite clunky, and it's not clear how easily a user could pick apart steps of this process, i.e. grabbing the dictionary of types from the atom-typing process without going all the way to a fully-parametrized system.

**Comment by mattwthompson** [comment]
@mosdef-hub/mosdef-contributors this is a fairy sizeable start to reworking some of the guts of foyer. Could you grab these changes and run some test or production systems?

You can do something like this to grab these changes in a new branch
```
git remote add https://github.com/mattwthompson/foyer
git fetch matt
git checkout -b matt/separate-apply
git checkout -b separate-apply
```

**Comment by ahy3nz** [comment]
Did a workflow with this version of foyer, parameters looked good and simulation ran fine

**Comment by rmatsum836** [comment]
I used this version of foyer and Python 3.7.3 to build a solvent-ionic liquid system.  The system was atomtyped correctly and the simulations are running fine.

**Comment by ptc2ug** [comment]
where are workflows currently shared? are they on the MoSDeF site?

On Jun 11, 2019, at 1:19 PM, Ray Matsumoto <notifications@github.com<mailto:notifications@github.com>> wrote:


I used this version of foyer and Python 3.7.3 to build a solvent-ionic liquid system. The system was atomtyped correctly and the simulations are running fine.

**Comment by justinGilmer** [comment]
@ptc2ug we currently dont have a place where these are shared. 

@mattwthompson I also pulled these changes and have been able to atomtype my alkylsilane tethered monolayers successfully with this update.

**Pull request merged**
