### PR TITLE
Add conftest.py to store pytest fixtures

### PR DESCRIPTION
**Pull request by mattwthompson**
### PR Summary:
Same idea as #242 but using @ctk3b's suggestion of `@pytest.fixture(scope="session")`

Can't really verify on CI that the extraneous files aren't being written, but they're not in my local directory. Somebody else should grab these changes and runs tests to see that it works for them as well.

### PR Checklist
------------
 - [ ] Includes appropriate unit test(s)
 - [ ] Appropriate docstring(s) are added/updated
 - [ ] Code is (approximately) PEP8 compliant
 - [ ] Issue(s) raised/addressed?

### CODE REVIEW

**Comment by ahy3nz** [comment]
It looks like tests with the pytest `scope=session` flag never get tested. It's not like they get skipped (`has_mbuild=True` and the testing output doesn't show the tests were skipped). Initially I didn't see any files being written so I thought it was working well, but I think it's because the tests aren't being run. This might just mean we have to learn more about this pytest fixture
```
(py36) ayang41@DeltaDurian:~/Programs/foyer/foyer/tests$ pytest -v test_forcefield.py --disable-warnings
================================== test session starts ===================================
platform darwin -- Python 3.6.7, pytest-4.5.0, py-1.8.0, pluggy-0.11.0 -- /Users/ayang41/anaconda3/envs/py36/bin/python
cachedir: .pytest_cache
rootdir: /Users/ayang41/Programs/foyer
collected 17 items

test_forcefield.py::test_load_files PASSED                                         [  5%]
test_forcefield.py::test_duplicate_type_definitions PASSED                         [ 11%]
test_forcefield.py::test_missing_type_definitions PASSED                           [ 17%]
test_forcefield.py::test_from_parmed PASSED                                        [ 23%]
test_forcefield.py::test_from_mbuild PASSED                                        [ 29%]
test_forcefield.py::test_preserve_resname PASSED                                   [ 35%]
test_forcefield.py::test_apply_residues PASSED                                     [ 41%]
test_forcefield.py::test_from_mbuild_customtype PASSED                             [ 47%]
test_forcefield.py::test_improper_dihedral PASSED                                  [ 52%]
test_forcefield.py::test_residue_map PASSED                                        [ 58%]
test_forcefield.py::test_independent_residues_molecules PASSED                     [ 64%]
test_forcefield.py::test_independent_residues_atoms PASSED                         [ 70%]
test_forcefield.py::test_topology_precedence PASSED                                [ 76%]
test_forcefield.py::test_missing_topo_params[ethane-angle-typo.xml-kwargs0] PASSED [ 82%]
test_forcefield.py::test_missing_topo_params[ethane-dihedral-typo.xml-kwargs1] PASSED [ 88%]
test_forcefield.py::test_overrides_space PASSED                                    [ 94%]
test_forcefield.py::test_assert_bonds PASSED                                       [100%]

========================= 17 passed, 41 warnings in 9.16 seconds =========================
```

**Comment by mattwthompson** [comment]
Right, we don't actually check for this after the tests run. Maybe there should be something in the CI scripts to check for extraneous files like these (before the VM gets nuked)?

If you run the same tests on `master` it should have those files, like this:

```
(pytest-scope)$ git checkout master 
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.
(mosdef) [Clausius] ~/software/foyer
(master)$ pytest -q foyer/tests/test_forcefield.py --disable-warnings
.....................                                                    [100%]
21 passed, 62 warnings in 10.73 seconds
(mosdef) [Clausius] ~/software/foyer
(master)$ ls *xml *bib
ethane-multi.bib	ethane.bib		opls-snippet.xml
(mosdef) [Clausius] ~/software/foyer
(master)$ rm *xml *bib
(mosdef) [Clausius] ~/software/foyer
(master)$ git checkout pytest-scope 
Switched to branch 'pytest-scope'
(mosdef) [Clausius] ~/software/foyer
(pytest-scope)$ pytest -q foyer/tests/test_forcefield.py --disable-warnings
.................                                                        [100%]
17 passed, 49 warnings in 7.57 seconds
(mosdef) [Clausius] ~/software/foyer
(pytest-scope)$ ls *xml *bib
ls: *bib: No such file or directory
ls: *xml: No such file or directory

**Comment by mattwthompson** [comment]
Oops I didn't notice that those 4 tests aren't being run at all (21 vs 17 on the different branches).

**Comment by ctk3b** [comment]
Ah sorry I did not phrase my suggestions accurately. I think you want to do this:

https://docs.pytest.org/en/latest/fixture.html#conftest-py-sharing-fixture-functions

Basically take the existing 
```
@pytest.fixture(autouse=True)
def initdir(self, tmpdir):
    tmpdir.chdir()
```

And put it in `conftest.py`

Sorry for the confusion.

If you have other reasons for wanting to use test classes then by all means

**Comment by mattwthompson** [comment]
So moving that fixture into a `conftest.py` seems to do the trick. Note that this uses `autouse=True` instead of `scope="session"`, but I I think that's what you mean to propose?


```
(pytest-scope *)$ pytest -q foyer/tests/test_forcefield.py --disable-warnings  ; ls *xml *bib
.....................                                                    [100%]
21 passed, 62 warnings in 10.34 seconds
ls: *bib: No such file or directory
ls: *xml: No such file or directory

**Comment by ctk3b** [comment]
> I think that's what you mean to propose?

Yup - sorry for the hastily written suggestion

**Pull request merged**
