### PR TITLE
Add gitter badge to README

### PR DESCRIPTION
**Pull request by justinGilmer**

### CODE REVIEW

**Comment by justinGilmer** [comment]
One more time @mosdef-hub/mosdef-contributors

**Comment by mattwthompson** [comment]
LGTM https://github.com/mosdef-hub/foyer/blob/2b6fec091b07b74d5b35d8f8fc6d73b6ffe8547d/README.md

**Comment by ahy3nz** [comment]
Evidently github doesn't value my opinion

**Comment by mattwthompson** [comment]
Fixed (I hadn't added that team to this repo like I did in mbuild)

**Pull request merged**
