### PR TITLE
Mock some requests in tests

### PR DESCRIPTION
**Pull request by mattwthompson**
#211 

The multiple refs test is failing since I can't figure out how to mock it to different values

This is based off of https://realpython.com/testing-third-party-apis-with-mocks, maybe better ways to do this

### CODE REVIEW

**Comment by mattwthompson** [comment]
Okay, the first test passes now.

**Comment by mattwthompson** [comment]
This might be something you can do a better job of, @umesh-timalsina? It's a low priority but would be a nice feature.

**Comment by umesh-timalsina** [comment]
Yeah I will take a stab at this PR. Starting with : we should change the way we have written the requests function call assuming that it will always pass [here](https://github.com/mosdef-hub/foyer/blob/90acba0d5ebb9df248eccf58b783d1e29bc6b57a/foyer/forcefield.py#L837).

**Comment by mattwthompson** [comment]
Sorry for the notifications, I am no longer trying to mock stuff but instead using this branch to fix another issue. Hopefully the git history is salvageable enough to anybody trying to solve the original issue of mocking requests.

**Pull request closed without merging**
