### PR TITLE
Switch to conda yml files

### PR DESCRIPTION
**Pull request by jennyfothergill**
### PR Summary:
If this is merged, we will need to modify [mbuild azure pipeline bleeding tests](https://github.com/mosdef-hub/mbuild/blob/5a9c77cad728d6aa8024a21eebfcd9c554638f00/azure-pipelines.yml#L154 ).

This may be a good case for using ~yq~ to combine the two ymls into one. edit: I used [conda-merge](https://github.com/amitbeka/conda-merge)

### PR Checklist
------------
 - [ ] Includes appropriate unit test(s)
 - [ ] Appropriate docstring(s) are added/updated 
 - [ ] Code is (approximately) PEP8 compliant
 - [ ] Issue(s) raised/addressed?

### CODE REVIEW

**Comment by jennyfothergill** [comment]
@daico007 I think this may affect #394, so I'd like your take on it :)

**Comment by jennyfothergill** [comment]
@umesh-timalsina do we know why the codecov tests are never completing?

**Review by daico007 — APPROVED** [review]
LGTM!

**Review by justinGilmer — APPROVED** [review]
Added a small edit to the dockerfile `sed` command. It was missing the `&& \` operator to continue to the next line.

**Pull request merged**
